import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import * as api from '../lib/api'

// Test data
const mockOrgId = '11111111-1111-1111-1111-111111111111'
const mockAdminUserId = 'admin-user-id'

const mockInvite = {
  id: 'invite-1',
  organisation_id: mockOrgId,
  email: 'invitee@example.com',
  token: 'test-invite-token-123',
  invited_by: mockAdminUserId,
  created_at: '2026-01-01T00:00:00Z',
  expires_at: '2027-01-08T00:00:00Z', // Future date
}

const mockExpiredInvite = {
  ...mockInvite,
  id: 'invite-2',
  expires_at: '2023-01-01T00:00:00Z', // Past date
}

/** Stub global fetch with a single JSON response. */
function mockFetch(body: unknown, ok = true) {
  const text = body === undefined ? '' : JSON.stringify(body)
  const fetchMock = vi.fn().mockResolvedValue({
    ok,
    json: async () => body,
    text: async () => text,
  })
  vi.stubGlobal('fetch', fetchMock)
  return fetchMock
}

describe('Organisation Invites', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  describe('Admin creating invites', () => {
    it('should allow admin to create an invite', async () => {
      const fetchMock = mockFetch(mockInvite)

      await api.createInvite({
        organisation_id: mockOrgId,
        email: 'invitee@example.com',
      })

      expect(fetchMock).toHaveBeenCalledWith(
        '/api/data/org-invites',
        expect.objectContaining({
          method: 'POST',
          body: JSON.stringify({
            organisation_id: mockOrgId,
            email: 'invitee@example.com',
          }),
        }),
      )
    })

    it('should generate a unique token for the invite', async () => {
      mockFetch(mockInvite)

      const data = await api.createInvite({
        organisation_id: mockOrgId,
        email: 'invitee@example.com',
      })

      // Token is generated by the database via default value
      expect(data.token).toBeDefined()
      expect(data.token!.length).toBeGreaterThan(0)
    })
  })

  describe('User accepting invite via token', () => {
    it('should find invite by token', async () => {
      const fetchMock = mockFetch(mockInvite)

      const data = await api.getInviteByToken('test-invite-token-123')

      expect(data).toEqual(mockInvite)
      expect(fetchMock.mock.calls[0][0]).toContain(
        '/api/data/org-invites?token=test-invite-token-123',
      )
    })

    it('should add user as member when accepting invite', async () => {
      const fetchMock = mockFetch({ ...mockInvite, id: 'member-1' })

      await api.addOrgMember({
        organisation_id: mockOrgId,
        user_id: 'new-user-id',
        role: 'member',
      })

      expect(fetchMock).toHaveBeenCalledWith(
        '/api/data/org-members',
        expect.objectContaining({ method: 'POST' }),
      )
    })

    it('should delete invite after acceptance', async () => {
      const fetchMock = mockFetch(undefined)

      await api.deleteInvite(mockInvite.id)

      expect(fetchMock).toHaveBeenCalledWith(
        '/api/data/org-invites',
        expect.objectContaining({
          method: 'DELETE',
          body: JSON.stringify({ id: mockInvite.id }),
        }),
      )
    })
  })

  describe('Expired invite handling', () => {
    it('should detect expired invites', () => {
      const now = new Date()
      const expiresAt = new Date(mockExpiredInvite.expires_at)

      expect(expiresAt < now).toBe(true)
    })

    it('should not accept expired invites', async () => {
      // The application logic should check expiration before accepting
      const isExpired = (invite: typeof mockExpiredInvite) => {
        if (!invite.expires_at) return false
        return new Date(invite.expires_at) < new Date()
      }

      expect(isExpired(mockExpiredInvite)).toBe(true)
      expect(isExpired(mockInvite)).toBe(false) // Non-expired invite
    })
  })

  describe('Non-admin cannot create invites', () => {
    it('should not allow regular member to create invite', async () => {
      // Authorisation is enforced server-side; the client surfaces the error
      mockFetch('Forbidden', false)

      await expect(
        api.createInvite({
          organisation_id: mockOrgId,
          email: 'invitee@example.com',
        }),
      ).rejects.toThrow()
    })
  })

  describe('Cancelling invites', () => {
    it('should allow admin to cancel pending invite', async () => {
      mockFetch(undefined)

      await expect(api.deleteInvite(mockInvite.id)).resolves.toBeUndefined()
    })
  })
})
